#tree -fi src/ --dirsfirst -F | grep -i -E '\.h|\.c'
set(SOURCES
    #src/arch/freertos/csp_clock.c
    #src/arch/freertos/csp_malloc.c
    #src/arch/freertos/csp_queue.c
    #src/arch/freertos/csp_semaphore.c
    #src/arch/freertos/csp_system.c
    #src/arch/freertos/csp_thread.c
    #src/arch/freertos/csp_time.c
    #src/arch/macosx/csp_clock.c
    #src/arch/macosx/csp_malloc.c
    #src/arch/macosx/csp_queue.c
    #src/arch/macosx/csp_semaphore.c
    #src/arch/macosx/csp_system.c
    #src/arch/macosx/csp_thread.c
    #src/arch/macosx/csp_time.c
    #src/arch/macosx/pthread_queue.c
    src/arch/posix/csp_clock.c
    src/arch/posix/csp_malloc.c
    src/arch/posix/csp_queue.c
    src/arch/posix/csp_semaphore.c
    src/arch/posix/csp_system.c
    src/arch/posix/csp_thread.c
    src/arch/posix/csp_time.c
    src/arch/posix/pthread_queue.c
    #src/arch/windows/csp_clock.c
    #src/arch/windows/csp_malloc.c
    #src/arch/windows/csp_queue.c
    #src/arch/windows/csp_semaphore.c
    #src/arch/windows/csp_system.c
    #src/arch/windows/csp_thread.c
    #src/arch/windows/csp_time.c
    #src/arch/windows/windows_queue.c
    #src/arch/windows/windows_queue.h
    src/arch/csp_system.c
    src/arch/csp_time.c
    #src/bindings/python/pycsp.c
    src/crypto/csp_hmac.c
    src/crypto/csp_sha1.c
    src/crypto/csp_xtea.c
    src/drivers/can/can_socketcan.c
    #src/drivers/usart/usart_kiss.c
    src/drivers/usart/usart_linux.c
    #src/drivers/usart/usart_windows.c
    src/external/csp_debug.c
    src/interfaces/csp_if_can.c
    src/interfaces/csp_if_can_pbuf.c
    src/interfaces/csp_if_can_pbuf.h
    src/interfaces/csp_if_i2c.c
    src/interfaces/csp_if_kiss.c
    src/interfaces/csp_if_lo.c
    src/interfaces/csp_if_zmqhub.c
    src/rtable/csp_rtable.c
    src/rtable/csp_rtable_cidr.c
    src/rtable/csp_rtable_internal.h
    src/rtable/csp_rtable_static.c
    src/transport/csp_rdp.c
    src/transport/csp_transport.h
    src/transport/csp_udp.c
    src/csp_bridge.c
    src/csp_buffer.c
    src/csp_conn.c
    src/csp_conn.h
    src/csp_crc32.c
    src/csp_debug.c
    src/csp_dedup.c
    src/csp_dedup.h
    src/csp_endian.c
    src/csp_hex_dump.c
    src/csp_iflist.c
    src/csp_init.c
    src/csp_init.h
    src/csp_io.c
    src/csp_io.h
    src/csp_port.c
    src/csp_port.h
    src/csp_promisc.c
    src/csp_promisc.h
    src/csp_qfifo.c
    src/csp_qfifo.h
    src/csp_route.c
    src/csp_service_handler.c
    src/csp_services.c
    src/csp_sfp.c
)

# tree -fi include/ --dirsfirst -F | grep -i '\.h'
set(PUB_HEADERS
)
